sudo: false

notifications:
  email: false

language: go

os:
  - linux
  - osx

env:
  - ARCH=x86_64

before_install:
  - git fetch --unshallow
  - go get -u github.com/go-swagger/go-swagger/cmd/swagger

before_script:
  - make cmd/fukurod-server/main.go

script:
  - make
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        mkdir -p views;
        export version=$(git describe);
    fi

after_success:
  - if [ "$TRAVIS_OS_NAME" = "linux" -a "$TRAVIS_BRANCH" = "master" -a "$DC" = "dmd" ]; then
        echo "uploading docker image...";
    fi
