sudo: required

notifications:
  email: false

services:
  - docker

addons:
  apt:
    packages:
      - libevent-dev

language: d

d:
  - dmd-2.074.0

matrix:
  allow_failures:
    - d: ldc-1.1.1

os:
  - linux
  - osx

env:
  - ARCH=x86_64

cache:
  directories:
    - $HOME/.dub

before_install:
  - git fetch --unshallow

script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        docker run --rm -it -v $PWD:/src docker-fukuro dub test || exit 1
        ./archive.sh || exit 1;
        mkdir -p views;
        git describe > views/version;
        export version=$(cat views/version);
        docker build -t $MOECOOP_IMAGE:$version .;
        docker run $MOECOOP_IMAGE:$version -h || exit 1;
        docker images $MOECOOP_IMAGE:$version;
    else
        dub test || exit 1;
    fi

after_success:
  - if [ "$TRAVIS_OS_NAME" = "linux" -a "$TRAVIS_BRANCH" = "master" -a "$DC" = "dmd" ]; then
        echo "uploading docker image...";
        docker tag $MOECOOP_IMAGE:$version $MOECOOP_IMAGE;
        docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        docker push $MOECOOP_IMAGE:$version;
        docker push $MOECOOP_IMAGE:latest;
    fi
