sudo: required

notifications:
  email: false

services:
  - docker

addons:
  apt:
    packages:
      - libevent-dev

language: d

d:
  - dmd-2.087.1
  - ldc-1.17.0

matrix:
  allow_failures:
    - d: ldc-1.17.0
    - os: osx

os:
  - linux
  - osx

env:
  - ARCH=x86_64

cache:
  directories:
    - $HOME/.dub

before_install:
  - git fetch --unshallow
  - dub fetch doveralls

before_script:
  - dub upgrade

script:
  - dub test --coverage
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        ./archive.sh || exit 1;
        mkdir -p views;
        export version=$(git describe);
        docker build -t $MOECOOP_IMAGE:$version .;
        docker run $MOECOOP_IMAGE:$version ./fukurod -h || exit 1;
        docker images $MOECOOP_IMAGE:$version;
    fi

after_success:
  - dub run doveralls
  - if [ "$TRAVIS_OS_NAME" = "linux" -a "$TRAVIS_BRANCH" = "master" -a "$DC" = "dmd" ]; then
        echo "uploading docker image...";
        docker tag $MOECOOP_IMAGE:$version $MOECOOP_IMAGE;
        echo "$DOCKER_PASSWORD" | docker login -u="$DOCKER_USERNAME" --password-stdin;
        docker push $MOECOOP_IMAGE:$version;
        docker push $MOECOOP_IMAGE:latest;
        docker login -u=_ -p="$HEROKU_TOKEN" registry.heroku.com;
        docker tag $MOECOOP_IMAGE:latest registry.heroku.com/moecoop-server/web;
        docker push registry.heroku.com/moecoop-server/web;
        echo "machine app.arukas.io login $ARUKAS_JSON_API_TOKEN password $ARUKAS_JSON_API_SECRET" > $HOME/.netrc;
        ./update-arukas.sh $MOECOOP_IMAGE:$version;
    fi
