platform:
  - x86
  - x64

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

environment:
  matrix:
    - DC: dmd
      DVersion: 2.080.0
    - DC: ldc
      DVersion: 1.9.0

matrix:
  allow_failures:
    - DC: ldc

skip_tags: true
branches:
  except:
    - sandbox

cache:
  - '%APPDATA%\dub'

install:
  - ps: function SetUpDCompiler
        {
            if($env:DC -eq "dmd"){
              if($env:platform -eq "x86"){
                $env:DConf = "m32";
              }
              elseif($env:platform -eq "x64"){
                $env:DConf = "m64";
              }
              echo "downloading ...";
              $env:toolchain = "msvc";
              $version = $env:DVersion;
              Invoke-WebRequest "http://downloads.dlang.org/releases/2.x/$($version)/dmd.$($version).windows.7z" -OutFile "c:\dmd.7z";
              echo "finished.";
              pushd c:\\;
              7z x dmd.7z > $null;
              popd;
            }
            elseif($env:DC -eq "ldc"){
              if($env:platform -eq "x86"){
                $env:DConf = "m32";
              }
              elseif($env:platform -eq "x64"){
                $env:DConf = "m64";
              }
              echo "downloading ...";
              $env:toolchain = "msvc";
              $version = $env:DVersion;
              Invoke-WebRequest "https://github.com/ldc-developers/ldc/releases/download/v$($version)/ldc2-$($version)-windows-$($env:platform).7z" -OutFile "c:\ldc.7z";
              echo "finished.";
              pushd c:\\;
              7z x ldc.7z > $null;
              mv ldc2-$($version)-windows-$($env:platform) ldc2;
              popd;
            }
        }
  - ps: SetUpDCompiler

before_build:
  - git submodule init
  - git submodule update
  - ps: if($env:platform -eq "x86"){
            $env:compilersetupargs = "x86";
            $env:Darch = "x86";
        }
        elseif($env:platform -eq "x64"){
            $env:compilersetupargs = "amd64";
            $env:Darch = "x86_64";
        }
  - ps : if($env:DC -eq "dmd"){
           $env:PATH += ";C:\dmd2\windows\bin;";
         }
         elseif($env:DC -eq "ldc"){
           $env:PATH += ";C:\ldc2\bin";
           $env:DC = "ldc2";
         }
  - ps: $env:compilersetup = "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall";
  - '"%compilersetup%" %compilersetupargs%'

build_script:
  - echo dummy build script - dont remove me

test_script:
  - echo %APPVEYOR_JOB_NAME%
  - echo %PLATFORM%
  - echo %DC%
  - echo %PATH%
  - '%DC% --version'
  - dub --version
  - dub upgrade
  - dub test --arch=%Darch% --compiler=%DC%
